# Generated by Django 4.1.3 on 2022-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_post_approved_posttag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
